"""Build plan and lockfile serialization.

A BuildPlan is the resolver's output: a fully validated, dependency-
ordered set of packages, ready for M2's fetch/layer machinery. The
lockfile is its TOML serialization — deterministic so that identical
resolver inputs always produce byte-identical lockfile text.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path


@dataclass(frozen=True)
class BaseInfo:
    name: str
    os_version: str | None = None
    kickstart_version: str | None = None
    dos_type: str | None = None


@dataclass(frozen=True)
class ResolvedPackage:
    name: str
    version: str
    options: dict = field(default_factory=dict)
    recipe_path: str = ""
    recipe_sha256: str = ""
    # kind ("aminet" | "github" | "assets") -> resolved fields (version
    # substituted). Which one is actually fetched is decided by M2's
    # fetch.py at build time (assets wins when present); the lockfile
    # simply records every source the recipe declared.
    sources: dict = field(default_factory=dict)


@dataclass(frozen=True)
class RunEntry:
    """One resolved [[run]] entry from the manifest: a program the built
    image runs at boot. `stack` and `tooltypes` are post-merge — the
    manifest's answer over the recipe's [install].commands default over
    the sugar keys — so the builder applies them without re-consulting
    any recipe. `tooltypes` values follow icon.set_tool_types'
    convention: a string is NAME=value, True the bare valueless name,
    False removal (only meaningful for mode "wbstartup")."""
    command: str
    mode: str = "cli"
    args: str = ""
    stack: int | None = None
    output: str | None = None
    detach: bool = False
    tooltypes: tuple[tuple[str, str | bool], ...] = ()


@dataclass(frozen=True)
class HdfOptions:
    """The manifest's [hdf] table, verbatim strings ("64M") rather than
    bytes — the lockfile round-trips what the author wrote, and
    emit/hdf.py's caller converts at the last moment. `size` overrides
    the content-derived image size; `scratch` reserves an unformatted
    partition at the end of the disk."""
    size: str | None = None
    scratch: str | None = None


@dataclass(frozen=True)
class BuildPlan:
    base: BaseInfo
    base_package: ResolvedPackage
    machine: dict
    packages: tuple[ResolvedPackage, ...]
    output: tuple[str, ...]
    emit: tuple[str, ...]
    runs: tuple[RunEntry, ...] = ()
    hdf: HdfOptions = HdfOptions()
    # The manifest's own [emulator-config.<emitter>] tables, verbatim —
    # merged by emit.collect_emulator_config after every recipe's
    # directives, so the manifest wins on key conflict.
    emulator_config: dict = field(default_factory=dict)


def format_lockfile(plan: BuildPlan) -> str:
    """Serialize a BuildPlan to deterministic lockfile TOML text."""
    # Bare keys must come before any [table] header — once a header is
    # written, subsequent bare `key = value` lines belong to that table,
    # not the document root.
    lines = [
        "# Generated by `amibake resolve`. Do not hand-edit.",
        "",
        f"output = {toml_value(list(plan.output))}",
        f"emit = {toml_value(list(plan.emit))}",
    ]

    for emitter in sorted(plan.emulator_config):
        directives = plan.emulator_config[emitter]
        lines.append("")
        lines.append(f"[emulator-config.{emitter}]")
        for key in sorted(directives):
            lines.append(f"{toml_value(key)} = {toml_value(directives[key])}")

    if plan.hdf.size is not None or plan.hdf.scratch is not None:
        lines.append("")
        lines.append("[hdf]")
        if plan.hdf.size is not None:
            lines.append(f"size = {toml_value(plan.hdf.size)}")
        if plan.hdf.scratch is not None:
            lines.append(f"scratch = {toml_value(plan.hdf.scratch)}")

    lines.append("")
    lines.append("[base]")
    lines.append(f"name = {toml_value(plan.base.name)}")
    if plan.base.os_version is not None:
        lines.append(f"os-version = {toml_value(plan.base.os_version)}")
    if plan.base.kickstart_version is not None:
        lines.append(f"kickstart-version = {toml_value(plan.base.kickstart_version)}")
    if plan.base.dos_type is not None:
        lines.append(f"dos-type = {toml_value(plan.base.dos_type)}")
    lines.append(f"version = {toml_value(plan.base_package.version)}")
    lines.append(f"recipe-sha256 = {toml_value(plan.base_package.recipe_sha256)}")
    if plan.base_package.options:
        opts = ", ".join(
            f"{k} = {toml_value(v)}" for k, v in sorted(plan.base_package.options.items())
        )
        lines.append(f"options = {{ {opts} }}")
    for kind in sorted(plan.base_package.sources):
        src = plan.base_package.sources[kind]
        lines.append(f"[base.sources.{kind}]")
        for key in sorted(src):
            lines.append(f"{key} = {toml_value(src[key])}")

    lines.append("")
    lines.append("[machine]")
    for key in sorted(plan.machine):
        lines.append(f"{key} = {toml_value(plan.machine[key])}")

    for pkg in plan.packages:
        lines.append("")
        lines.append("[[package]]")
        lines.append(f"name = {toml_value(pkg.name)}")
        lines.append(f"version = {toml_value(pkg.version)}")
        lines.append(f"recipe-sha256 = {toml_value(pkg.recipe_sha256)}")
        if pkg.options:
            opts = ", ".join(
                f"{k} = {toml_value(v)}" for k, v in sorted(pkg.options.items())
            )
            lines.append(f"options = {{ {opts} }}")
        for kind in sorted(pkg.sources):
            src = pkg.sources[kind]
            lines.append(f"[package.sources.{kind}]")
            for key in sorted(src):
                lines.append(f"{key} = {toml_value(src[key])}")

    for run in plan.runs:
        lines.append("")
        lines.append("[[run]]")
        lines.append(f"command = {toml_value(run.command)}")
        lines.append(f"mode = {toml_value(run.mode)}")
        if run.args:
            lines.append(f"args = {toml_value(run.args)}")
        if run.stack is not None:
            lines.append(f"stack = {toml_value(run.stack)}")
        if run.output is not None:
            lines.append(f"output = {toml_value(run.output)}")
        if run.detach:
            lines.append(f"detach = {toml_value(run.detach)}")
        if run.tooltypes:
            tt = ", ".join(f"{name} = {toml_value(value)}"
                           for name, value in run.tooltypes)
            lines.append(f"tooltypes = {{ {tt} }}")

    return "\n".join(lines) + "\n"


def write_lockfile(plan: BuildPlan, path: Path) -> None:
    path.write_text(format_lockfile(plan))


def toml_value(value) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    if value is None:
        return '""'
    if isinstance(value, str):
        escaped = value.replace("\\", "\\\\").replace('"', '\\"')
        return f'"{escaped}"'
    if isinstance(value, list):
        return "[" + ", ".join(toml_value(v) for v in value) + "]"
    return str(value)
