"""Build plan and lockfile serialization.

A BuildPlan is the resolver's output: a fully validated, dependency-
ordered set of packages, ready for M2's fetch/layer machinery. The
lockfile is its TOML serialization — deterministic so that identical
resolver inputs always produce byte-identical lockfile text.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path


@dataclass(frozen=True)
class BaseInfo:
    name: str
    os_version: str | None = None
    kickstart_version: str | None = None
    dos_type: str | None = None


@dataclass(frozen=True)
class ResolvedPackage:
    name: str
    version: str
    options: dict = field(default_factory=dict)
    recipe_path: str = ""
    recipe_sha256: str = ""
    # kind ("aminet" | "github" | "assets") -> resolved fields (version
    # substituted). Which one is actually fetched is decided by M2's
    # fetch.py at build time (assets wins when present); the lockfile
    # simply records every source the recipe declared.
    sources: dict = field(default_factory=dict)


@dataclass(frozen=True)
class BuildPlan:
    base: BaseInfo
    base_package: ResolvedPackage
    machine: dict
    packages: tuple[ResolvedPackage, ...]
    output: tuple[str, ...]
    emit: tuple[str, ...]


def format_lockfile(plan: BuildPlan) -> str:
    """Serialize a BuildPlan to deterministic lockfile TOML text."""
    # Bare keys must come before any [table] header — once a header is
    # written, subsequent bare `key = value` lines belong to that table,
    # not the document root.
    lines = [
        "# Generated by `amibake resolve`. Do not hand-edit.",
        "",
        f"output = {toml_value(list(plan.output))}",
        f"emit = {toml_value(list(plan.emit))}",
    ]

    lines.append("")
    lines.append("[base]")
    lines.append(f"name = {toml_value(plan.base.name)}")
    if plan.base.os_version is not None:
        lines.append(f"os-version = {toml_value(plan.base.os_version)}")
    if plan.base.kickstart_version is not None:
        lines.append(f"kickstart-version = {toml_value(plan.base.kickstart_version)}")
    if plan.base.dos_type is not None:
        lines.append(f"dos-type = {toml_value(plan.base.dos_type)}")
    lines.append(f"version = {toml_value(plan.base_package.version)}")
    lines.append(f"recipe-sha256 = {toml_value(plan.base_package.recipe_sha256)}")
    if plan.base_package.options:
        opts = ", ".join(
            f"{k} = {toml_value(v)}" for k, v in sorted(plan.base_package.options.items())
        )
        lines.append(f"options = {{ {opts} }}")
    for kind in sorted(plan.base_package.sources):
        src = plan.base_package.sources[kind]
        lines.append(f"[base.sources.{kind}]")
        for key in sorted(src):
            lines.append(f"{key} = {toml_value(src[key])}")

    lines.append("")
    lines.append("[machine]")
    for key in sorted(plan.machine):
        lines.append(f"{key} = {toml_value(plan.machine[key])}")

    for pkg in plan.packages:
        lines.append("")
        lines.append("[[package]]")
        lines.append(f"name = {toml_value(pkg.name)}")
        lines.append(f"version = {toml_value(pkg.version)}")
        lines.append(f"recipe-sha256 = {toml_value(pkg.recipe_sha256)}")
        if pkg.options:
            opts = ", ".join(
                f"{k} = {toml_value(v)}" for k, v in sorted(pkg.options.items())
            )
            lines.append(f"options = {{ {opts} }}")
        for kind in sorted(pkg.sources):
            src = pkg.sources[kind]
            lines.append(f"[package.sources.{kind}]")
            for key in sorted(src):
                lines.append(f"{key} = {toml_value(src[key])}")

    return "\n".join(lines) + "\n"


def write_lockfile(plan: BuildPlan, path: Path) -> None:
    path.write_text(format_lockfile(plan))


def toml_value(value) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    if value is None:
        return '""'
    if isinstance(value, str):
        escaped = value.replace("\\", "\\\\").replace('"', '\\"')
        return f'"{escaped}"'
    if isinstance(value, list):
        return "[" + ", ".join(toml_value(v) for v in value) + "]"
    return str(value)
