"""Applies a manifest's resolved [[run]] entries to a built Tree.

Runs after every layer (base + packages): the entries name programs the
layers have already installed. Two mechanisms, matching how AmigaOS
itself starts things:

- mode "cli" entries render into one generated `S:AmiBake-Startup`
  script, executed from `S:User-Startup` by a fragment at order
  RUN_FRAGMENT_ORDER — after every package's own startup fragments
  (house convention keeps recipes at 0–99, in practice well below).
  A separate file rather than more User-Startup lines on purpose:
  someone inspecting the image sees "what AmiBake was told to run"
  distinct from "what packages installed", and re-running just the
  workload from a Shell is `Execute S:AmiBake-Startup`.

- mode "wbstartup" entries copy the program (plus its icon, patched
  with the resolved tool types) into `SYS:WBStartup/`, the drawer
  Workbench scans after LoadWB. The icon must already be installed
  beside the program (`<command>.info`) — generating a default icon
  from nothing is future work, see docs/limits.md.

A `Stack` line persists for subsequent entries (Execute runs the script
in the calling Shell's own process), documented in docs/manifest.md —
the base default isn't knowable portably, so nothing here guesses at
restoring it.
"""

from __future__ import annotations

from .icon import IconError, set_tool_types
from .paths import to_physical_path
from .plan import RunEntry
from .tree import Tree

RUN_SCRIPT_PATH = "S:AmiBake-Startup"
RUN_FRAGMENT_ORDER = 95
RUN_FRAGMENT_SOURCE = "amibake-run"


class RunError(Exception):
    pass


def apply_runs(tree: Tree, runs: tuple[RunEntry, ...]) -> Tree:
    """A clone of `tree` with every [[run]] entry applied; `tree` itself
    is never mutated (same contract as layer.apply_layer)."""
    if not runs:
        return tree
    tree = tree.clone()

    # Physical-path index of the tree, so `C:devsoak` finds the file a
    # layer installed as `SYS:C/devsoak` (Tree._key only collapses the
    # aliases paths.py maps; a run entry may legitimately use either
    # spelling).
    physical = {}
    for path in tree.paths():
        if ":" in path:
            physical[to_physical_path(path).lower()] = path

    script_blocks: list[str] = []
    for i, run in enumerate(runs):
        installed = physical.get(to_physical_path(run.command).lower())
        if installed is None:
            raise RunError(
                f"[[run]] entry {i} names {run.command!r}, which nothing in "
                f"this build installed — check the path against the package's "
                f"recipe (its [install].copy destinations), or add the package "
                f"that provides it")
        if run.mode == "wbstartup":
            _apply_wbstartup(tree, physical, run, i, installed)
        else:
            script_blocks.append(_render_cli_block(run, i))

    if script_blocks:
        header = "; Generated by AmiBake from the manifest's [[run]] entries."
        content = "\n\n".join([header, *script_blocks]) + "\n"
        tree.put(RUN_SCRIPT_PATH, content.encode("latin-1"))
        tree.add_user_startup(RUN_FRAGMENT_ORDER, RUN_FRAGMENT_SOURCE,
                              [f"Execute {RUN_SCRIPT_PATH}"])
    return tree


def _render_cli_block(run: RunEntry, index: int) -> str:
    lines = [f"; --- run[{index}]: {run.command} ---"]
    if run.stack is not None:
        lines.append(f"Stack {run.stack}")
    command = run.command
    if run.args:
        command += f" {run.args}"
    if run.output:
        # The Shell parses `>` wherever it appears; trailing keeps the
        # command's own arguments contiguous and readable.
        command += f" >{run.output}"
    if run.detach:
        command = f"Run >NIL: {command}"
    lines.append(command)
    return "\n".join(lines)


def _apply_wbstartup(tree: Tree, physical: dict[str, str], run: RunEntry,
                     index: int, installed: str) -> None:
    icon_installed = physical.get(to_physical_path(run.command).lower() + ".info")
    if icon_installed is None:
        raise RunError(
            f"[[run]] entry {index}: mode = \"wbstartup\" needs an icon, and "
            f"{run.command + '.info'!r} is not in this build — Workbench only "
            f"starts what has a Workbench icon. Install one beside the program "
            f"(the recipe's archive may ship it; [install].files can add one), "
            f"or start the program from a mode = \"cli\" entry instead")

    basename = installed.rpartition("/")[2].rpartition(":")[2]
    program = tree.get(installed)
    tree.put(f"SYS:WBStartup/{basename}", program.data, program.meta)

    icon = tree.get(icon_installed)
    try:
        patched = set_tool_types(icon.data, dict(run.tooltypes))
    except IconError as e:
        raise RunError(f"[[run]] entry {index}: {run.command}.info: {e}") from e
    tree.put(f"SYS:WBStartup/{basename}.info", patched, icon.meta)
